import { ProductItem, CertificateItem } from "@/types";

export const MOCK_CATEGORIES = [
  {
    id: "cat-1",
    name: "1 to 14 Mukhi Rudraksha",
    slug: "1-14-mukhi-rudraksha",
    description: "Authentic single beads directly harvested from eastern Himalayan foothills of Nepal (Sankhuwasabha & Dingla).",
  },
  {
    id: "cat-2",
    name: "Rare & Sacred Combinations",
    slug: "rare-sacred-rudraksha",
    description: "Naturally conjoined and uniquely formed sacred specimens like Gauri Shankar, Trijuti, and Ganesh Rudraksha.",
  },
  {
    id: "cat-3",
    name: "Rudraksha Malas & Rosaries",
    slug: "rudraksha-malas",
    description: "Traditional 108+1 japa rosaries and designer malas strung with natural silk and pure silver wire.",
  },
  {
    id: "cat-4",
    name: "Rudraksha Bracelets",
    slug: "rudraksha-bracelets",
    description: "Ergonomic wristbands crafted from hand-selected authentic Nepali beads with adjustable clasps.",
  },
  {
    id: "cat-5",
    name: "Silver Caps & Puja Accessories",
    slug: "puja-accessories",
    description: "Pure 925 sterling silver cappings, traditional teakwood storage boxes, and consecration essentials.",
  },
];

export const MOCK_CERTIFICATES: CertificateItem[] = [
  {
    id: "cert-1",
    productId: "prod-1",
    certificateNumber: "RK-DEMO-00001",
    mukhi: 1,
    origin: "Nepal (Sankhuwasabha)",
    dimensions: "24.5 x 18.2 mm",
    weightGrams: 4.12,
    inspectionDate: new Date("2026-01-15"),
    laboratory: "RudraKart Himalayan Gem & Botanical Lab (Academic Demo)",
    xrayStatus: "Single central seed chamber verified; no artificial embedding detected",
    microscopicCheck: "Complete natural uninterrupted Mukhi line; authentic thorny cellular ridges",
    verificationStatus: "VERIFIED",
  },
  {
    id: "cert-2",
    productId: "prod-2",
    certificateNumber: "RK-DEMO-00002",
    mukhi: 2,
    origin: "Nepal (Sankhuwasabha)",
    dimensions: "21.0 x 14.5 mm",
    weightGrams: 3.20,
    inspectionDate: new Date("2026-02-10"),
    laboratory: "RudraKart Himalayan Gem & Botanical Lab (Academic Demo)",
    xrayStatus: "Two distinct internal seed compartments observed",
    microscopicCheck: "Natural twin cleft lines intact; density standard 1.18 g/cm3",
    verificationStatus: "VERIFIED",
  },
  {
    id: "cert-5",
    productId: "prod-5",
    certificateNumber: "RK-DEMO-00005",
    mukhi: 5,
    origin: "Nepal (Dingla)",
    dimensions: "22.0 x 21.8 mm",
    weightGrams: 3.80,
    inspectionDate: new Date("2026-03-01"),
    laboratory: "RudraKart Himalayan Gem & Botanical Lab (Academic Demo)",
    xrayStatus: "Five natural radial seed cavities confirmed",
    microscopicCheck: "Standard natural Elaeocarpus ganitrus endocarp structure",
    verificationStatus: "VERIFIED",
  },
  {
    id: "cert-7",
    productId: "prod-7",
    certificateNumber: "RK-DEMO-00007",
    mukhi: 7,
    origin: "Nepal (Sankhuwasabha)",
    dimensions: "23.0 x 22.7 mm",
    weightGrams: 4.05,
    inspectionDate: new Date("2026-03-12"),
    laboratory: "RudraKart Himalayan Gem & Botanical Lab (Academic Demo)",
    xrayStatus: "Seven symmetrical internal seed cavities observed",
    microscopicCheck: "Pristine natural ridges; unbleached chemical-free surface",
    verificationStatus: "VERIFIED",
  },
  {
    id: "cert-14",
    productId: "prod-14",
    certificateNumber: "RK-DEMO-00014",
    mukhi: 14,
    origin: "Nepal (Sankhuwasabha)",
    dimensions: "26.5 x 26.1 mm",
    weightGrams: 5.20,
    inspectionDate: new Date("2026-03-18"),
    laboratory: "RudraKart Himalayan Gem & Botanical Lab (Academic Demo)",
    xrayStatus: "14 distinct internal seed cavities completely verified under digital radiograph",
    microscopicCheck: "Natural woody partitions; genuine uninterrupted spines with zero carving",
    verificationStatus: "VERIFIED",
  },
  {
    id: "cert-15",
    productId: "prod-15",
    certificateNumber: "RK-DEMO-00015",
    mukhi: 10,
    origin: "Nepal (Sankhuwasabha)",
    dimensions: "28.0 x 21.4 mm",
    weightGrams: 6.10,
    inspectionDate: new Date("2026-03-20"),
    laboratory: "RudraKart Himalayan Gem & Botanical Lab (Academic Demo)",
    xrayStatus: "Continuous botanical fusion observed; no glue or synthetic bonding material",
    microscopicCheck: "Natural organic joint with continuous woody fiber network",
    verificationStatus: "VERIFIED",
  },
];

export const MOCK_PRODUCTS: ProductItem[] = [
  {
    id: "prod-1",
    name: "1 Mukhi Savar Rudraksha (Nepal)",
    slug: "1-mukhi-rudraksha-nepal",
    description: "The rarest and most revered single-mukhi formation found in nature. This Nepali Savar bead naturally grows conjoined with a supporting base bead, displaying a single undivided natural groove running from head to tail. Verified via X-ray imaging showing complete natural internal chamber formation.",
    price: 145000,
    mukhi: 1,
    isSpecial: true,
    origin: "Nepal (Sankhuwasabha)",
    size: "24.5 mm",
    weight: "4.12 grams",
    shape: "Natural Oval Savar",
    stock: 2,
    featured: true,
    isCertified: true,
    categoryId: "cat-2",
    category: MOCK_CATEGORIES[1],
    images: [
      {
        id: "img-1",
        url: "/images/products/1-mukhi-savar-rudraksha.jpg",
        altText: "Authentic 1 Mukhi Savar Rudraksha from Sankhuwasabha Nepal showing natural single ridge and Savar formation",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    certificates: [MOCK_CERTIFICATES[0]],
  },
  {
    id: "prod-2",
    name: "2 Mukhi Dwi Mukhi Rudraksha (Nepal)",
    slug: "2-mukhi-rudraksha-nepal",
    description: "Authentic two-faced Nepali Rudraksha representing the sacred Ardhanarishvara union. Features two clearly defined natural clefts traversing symmetrically across the bead with deep, prominent ridges.",
    price: 9500,
    mukhi: 2,
    isSpecial: false,
    origin: "Nepal (Sankhuwasabha)",
    size: "21.0 mm",
    weight: "3.20 grams",
    shape: "Natural Crescent Oval",
    stock: 6,
    featured: true,
    isCertified: true,
    categoryId: "cat-1",
    category: MOCK_CATEGORIES[0],
    images: [
      {
        id: "img-2",
        url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=82",
        altText: "2 Mukhi Rudraksha Nepal",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    certificates: [MOCK_CERTIFICATES[1]],
  },
  {
    id: "prod-3",
    name: "3 Mukhi Agni Rudraksha (Nepal)",
    slug: "3-mukhi-rudraksha-nepal",
    description: "Authentic three-mukhi bead from Dingla region of eastern Nepal. Features three distinct equidistant natural ridges, symbolizing pure vitality and energy.",
    price: 4500,
    mukhi: 3,
    isSpecial: false,
    origin: "Nepal (Dingla)",
    size: "18.5 mm",
    weight: "2.95 grams",
    shape: "Natural Round-Oval",
    stock: 12,
    featured: false,
    isCertified: true,
    categoryId: "cat-1",
    category: MOCK_CATEGORIES[0],
    images: [
      {
        id: "img-3",
        url: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=82",
        altText: "3 Mukhi Rudraksha Nepal",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-4",
    name: "4 Mukhi Brahma Rudraksha (Nepal)",
    slug: "4-mukhi-rudraksha-nepal",
    description: "Natural 4-faced bead harvested from high-altitude groves in eastern Nepal. Four clean, deeply grooved lines run from pole to pole without artificial carving.",
    price: 3500,
    mukhi: 4,
    isSpecial: false,
    origin: "Nepal (Sankhuwasabha)",
    size: "19.0 mm",
    weight: "3.10 grams",
    shape: "Spherical",
    stock: 15,
    featured: false,
    isCertified: true,
    categoryId: "cat-1",
    category: MOCK_CATEGORIES[0],
    images: [
      {
        id: "img-4",
        url: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=900&q=82",
        altText: "4 Mukhi Rudraksha Nepal",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-5",
    name: "5 Mukhi Collector Grade Rudraksha (Nepal)",
    slug: "5-mukhi-rudraksha-nepal",
    description: "Premium large-sized (22mm+) 5 Mukhi bead representing Lord Shiva (Kalagni Rudra). Selected from prime crop harvest with flawless symmetry, deep natural facets, and dense woody texture.",
    price: 1800,
    mukhi: 5,
    isSpecial: false,
    origin: "Nepal (Dingla)",
    size: "22.0 mm",
    weight: "3.80 grams",
    shape: "Natural Round",
    stock: 45,
    featured: true,
    isCertified: true,
    categoryId: "cat-1",
    category: MOCK_CATEGORIES[0],
    images: [
      {
        id: "img-5",
        url: "https://images.unsplash.com/photo-1609743522653-52354461eb27?auto=format&fit=crop&w=900&q=82",
        altText: "5 Mukhi Rudraksha Collector Bead",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    certificates: [MOCK_CERTIFICATES[2]],
  },
  {
    id: "prod-6",
    name: "6 Mukhi Kartikeya Rudraksha (Nepal)",
    slug: "6-mukhi-rudraksha-nepal",
    description: "Six-faced authentic Nepali Rudraksha representing Lord Kartikeya. Known for high botanical density, sharp thorny ridges, and symmetrical line distribution.",
    price: 4200,
    mukhi: 6,
    isSpecial: false,
    origin: "Nepal (Sankhuwasabha)",
    size: "20.5 mm",
    weight: "3.40 grams",
    shape: "Natural Round",
    stock: 14,
    featured: false,
    isCertified: true,
    categoryId: "cat-1",
    category: MOCK_CATEGORIES[0],
    images: [
      {
        id: "img-6",
        url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=82",
        altText: "6 Mukhi Rudraksha Nepal",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-7",
    name: "7 Mukhi Mahalakshmi Rudraksha (Nepal)",
    slug: "7-mukhi-rudraksha-nepal",
    description: "Auspicious 7-faced Nepali Rudraksha representing Goddess Mahalakshmi. Highly prized for its distinct deep golden-brown luster and clearly articulated seven facets.",
    price: 12000,
    mukhi: 7,
    isSpecial: false,
    origin: "Nepal (Sankhuwasabha)",
    size: "23.0 mm",
    weight: "4.05 grams",
    shape: "Natural Round",
    stock: 8,
    featured: true,
    isCertified: true,
    categoryId: "cat-1",
    category: MOCK_CATEGORIES[0],
    images: [
      {
        id: "img-7",
        url: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=900&q=82",
        altText: "7 Mukhi Mahalakshmi Rudraksha",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    certificates: [MOCK_CERTIFICATES[3]],
  },
  {
    id: "prod-8",
    name: "8 Mukhi Ashta-Murti Ganesh Rudraksha (Nepal)",
    slug: "8-mukhi-rudraksha-nepal",
    description: "Natural eight-mukhi Rudraksha associated with Lord Ganesha. Premium high-altitude specimen featuring deep contours and exceptional durability.",
    price: 18500,
    mukhi: 8,
    isSpecial: false,
    origin: "Nepal (Dingla)",
    size: "21.5 mm",
    weight: "3.65 grams",
    shape: "Natural Round",
    stock: 5,
    featured: false,
    isCertified: true,
    categoryId: "cat-1",
    category: MOCK_CATEGORIES[0],
    images: [
      {
        id: "img-8",
        url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=82",
        altText: "8 Mukhi Rudraksha Nepal",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-9",
    name: "9 Mukhi Navadurga Rudraksha (Nepal)",
    slug: "9-mukhi-rudraksha-nepal",
    description: "Sacred 9-mukhi Nepali Rudraksha representing the nine forms of Goddess Durga (Navashakti). Large, well-balanced bead with 9 prominent natural lines.",
    price: 26000,
    mukhi: 9,
    isSpecial: false,
    origin: "Nepal (Sankhuwasabha)",
    size: "22.8 mm",
    weight: "3.90 grams",
    shape: "Natural Round",
    stock: 4,
    featured: true,
    isCertified: true,
    categoryId: "cat-1",
    category: MOCK_CATEGORIES[0],
    images: [
      {
        id: "img-9",
        url: "https://images.unsplash.com/photo-1601821765780-754fa98637c1?auto=format&fit=crop&w=900&q=82",
        altText: "9 Mukhi Navadurga Rudraksha",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-10",
    name: "10 Mukhi Dashamukhi Rudraksha (Nepal)",
    slug: "10-mukhi-rudraksha-nepal",
    description: "Ten-faced Nepali Rudraksha representing Lord Mahavishnu and the ten directions (Digpalas). Excellent spherical formation with ten distinct facets.",
    price: 34000,
    mukhi: 10,
    isSpecial: false,
    origin: "Nepal (Sankhuwasabha)",
    size: "23.5 mm",
    weight: "4.15 grams",
    shape: "Natural Round",
    stock: 3,
    featured: false,
    isCertified: true,
    categoryId: "cat-1",
    category: MOCK_CATEGORIES[0],
    images: [
      {
        id: "img-10",
        url: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?auto=format&fit=crop&w=900&q=82",
        altText: "10 Mukhi Rudraksha Nepal",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-14",
    name: "14 Mukhi Devamani Rudraksha (Nepal)",
    slug: "14-mukhi-rudraksha-nepal",
    description: "Among the rarest and most treasured of all higher Mukhis. Known as the Devamani (Gem of the Gods) and associated with Lord Hanuman and Lord Shiva. Large collector size with 14 natural lines traversing the entire sphere.",
    price: 210000,
    mukhi: 14,
    isSpecial: true,
    origin: "Nepal (Sankhuwasabha)",
    size: "26.5 mm",
    weight: "5.20 grams",
    shape: "Natural Spherical",
    stock: 1,
    featured: true,
    isCertified: true,
    categoryId: "cat-2",
    category: MOCK_CATEGORIES[1],
    images: [
      {
        id: "img-14",
        url: "https://images.unsplash.com/photo-1619119069152-a2b331eb392a?auto=format&fit=crop&w=900&q=82",
        altText: "14 Mukhi Devamani Rudraksha Nepal",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    certificates: [MOCK_CERTIFICATES[4]],
  },
  {
    id: "prod-15",
    name: "Gauri Shankar Sacred Conjoined Rudraksha",
    slug: "gauri-shankar-rudraksha-nepal",
    description: "Naturally united twin Rudraksha beads conjoined on the tree without human intervention. Symbolizes the divine union of Lord Shiva and Goddess Parvati. Outstanding natural bond strength and symmetrical beauty.",
    price: 55000,
    mukhi: null,
    isSpecial: true,
    origin: "Nepal (Sankhuwasabha)",
    size: "28.0 mm",
    weight: "6.10 grams",
    shape: "Naturally Joined Twin",
    stock: 2,
    featured: true,
    isCertified: true,
    categoryId: "cat-2",
    category: MOCK_CATEGORIES[1],
    images: [
      {
        id: "img-15",
        url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=82",
        altText: "Gauri Shankar Rudraksha Nepal",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
    certificates: [MOCK_CERTIFICATES[5]],
  },
  {
    id: "prod-16",
    name: "Natural Ganesh Rudraksha with Trunk Formation",
    slug: "ganesh-rudraksha-nepal",
    description: "A rare biological wonder where an organic trunk-like protrusion naturally extends from the body of the bead. Revered as an auspicious representation of Lord Ganesha.",
    price: 22000,
    mukhi: null,
    isSpecial: true,
    origin: "Nepal (Dingla)",
    size: "21.0 mm",
    weight: "3.50 grams",
    shape: "Trunk-Bearing Spherical",
    stock: 3,
    featured: true,
    isCertified: true,
    categoryId: "cat-2",
    category: MOCK_CATEGORIES[1],
    images: [
      {
        id: "img-16",
        url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=82",
        altText: "Ganesh Rudraksha Nepal",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-17",
    name: "108+1 Beads 5-Mukhi Nepali Japa Mala (8mm)",
    slug: "108-beads-5-mukhi-nepali-japa-mala",
    description: "Hand-crafted 108+1 sacred rosary strung with calibrated 8mm natural Nepali five-mukhi beads. Features traditional knotting between each bead and a vibrant saffron tassel.",
    price: 6500,
    mukhi: 5,
    isSpecial: false,
    origin: "Nepal",
    size: "8 mm beads (108+1 total)",
    weight: "48 grams",
    shape: "Uniform Spherical Beads",
    stock: 25,
    featured: false,
    isCertified: false,
    categoryId: "cat-3",
    category: MOCK_CATEGORIES[2],
    images: [
      {
        id: "img-17",
        url: "https://images.unsplash.com/photo-1528459105426-b9548367069b?auto=format&fit=crop&w=900&q=82",
        altText: "108 Beads 5 Mukhi Nepali Japa Mala",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-18",
    name: "Pure 925 Silver Capped 5-Mukhi Rudraksha Bracelet",
    slug: "silver-capped-5-mukhi-bracelet",
    description: "Elegant wrist bracelet crafted with selected 12mm Nepali five-mukhi Rudraksha beads encased in handcrafted 925 sterling silver caps with a secure lobster clasp.",
    price: 4800,
    mukhi: 5,
    isSpecial: false,
    origin: "Nepal",
    size: "12 mm beads (7.5 inch length)",
    weight: "18.5 grams",
    shape: "Beaded Bracelet",
    stock: 18,
    featured: false,
    isCertified: false,
    categoryId: "cat-4",
    category: MOCK_CATEGORIES[3],
    images: [
      {
        id: "img-18",
        url: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=82",
        altText: "Silver Capped Rudraksha Bracelet",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    id: "prod-19",
    name: "Carved Teakwood Velvet-Lined Rudraksha Storage Box",
    slug: "carved-teakwood-rudraksha-box",
    description: "Traditional Himalayan artisan-carved solid teakwood box with rich saffron velvet interior. Designed specifically to protect and energize sacred beads.",
    price: 2200,
    mukhi: null,
    isSpecial: false,
    origin: "Nepal (Patan Craft)",
    size: "15 x 10 x 8 cm",
    weight: "320 grams",
    shape: "Rectangular Box",
    stock: 30,
    featured: false,
    isCertified: false,
    categoryId: "cat-5",
    category: MOCK_CATEGORIES[4],
    images: [
      {
        id: "img-19",
        url: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=82",
        altText: "Carved Teakwood Storage Box",
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
];
